language: node_js
node_js: 
  - "stable"
services:
  - postgresql

before_install:
  - psql -c 'create database test' -U postgres
  
script: npm test
cache:
  directories:
    - "node_modules"
after_success:
  - "npm run coveralls"